---
version: 2

templates:
  cache: &cache
    key: v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
      - image: redis
      - image: postgres
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          <<: *cache
      - run: npm install
      - run: npm test
      - run: npm run integration-ci
      - save_cache:
          <<: *cache
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Send to Coveralls
          command: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
