---
version: 2

references:
  filter_all: &filter_all
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/

  filter_head: &filter_head
    filters:
      branches:
        only: master
      tags:
        only: stg

  filter_release: &filter_release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v[0-9]+\.[0-9]+\.[0-9]+(-[0-9])?/

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
      - image: redis
      - image: postgres
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: v2-node12-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v2-node12-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - run: npm run integration-ci
      - run: |
          if [[ "$CIRCLE_BRANCH" == "master" ]]; then
            cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
          fi

  deploy_package:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo "$NPMRC" > ~/.npmrc
          chmod 600 ~/.npmrc
          if [[ "$CIRCLE_TAG" = *-* ]]; then
            npm publish --tag=prerelease
          else
            npm publish
          fi

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          <<: *filter_all
      - deploy_package:
          <<: *filter_release
          context:
            - npm-publish
          requires:
            - test
