ALTER TABLE IF EXISTS pages
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS unpublished_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS republished_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
