ALTER TABLE IF EXISTS lists
ALTER COLUMN IF EXISTS created_at SET DEFAULT NOW(),
ALTER COLUMN IF EXISTS updated_at SET DEFAULT NOW();

ALTER TABLE IF EXISTS uris
ALTER COLUMN IF EXISTS created_at SET DEFAULT NOW(),
ALTER COLUMN IF EXISTS updated_at SET DEFAULT NOW();

ALTER TABLE IF EXISTS pages
ALTER COLUMN IF EXISTS created_at SET DEFAULT NOW(),
ALTER COLUMN IF EXISTS updated_at SET DEFAULT NOW();

ALTER TABLE IF EXISTS users
ALTER COLUMN IF EXISTS created_at SET DEFAULT NOW(),
ALTER COLUMN IF EXISTS updated_at SET DEFAULT NOW();
