ALTER TABLE IF EXISTS lists
ADD COLUMN IF NOT EXISTS site_id VARCHAR(255);

ALTER TABLE IF EXISTS pages
ADD COLUMN IF NOT EXISTS site_id VARCHAR(255);

ALTER TABLE IF EXISTS uris
ADD COLUMN IF NOT EXISTS site_id VARCHAR(255);
